version: ~> 1.0
os: linux
dist: xenial
language: minimal
services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1 /repo -output json /updateassemblyinfo

script:
  - sleep 15 # thx travis
  - docker info
  - docker build --rm=false --target=builder -t travis-gitversion:test .
  - docker run --rm travis-gitversion:test dotnet test

